global using Educonnect.Common.Service.Services;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using System.Net;
global using Grpc.Core;
global using static CommonGrpcService.Common;
global using static CommonGrpcService.FormBuf;
global using CommonGrpcService;
global using MediatR;
global using System.ComponentModel.DataAnnotations;
global using AutoMapper;
global using Educonnect.Common.Service.Entities;
global using Microsoft.Extensions.Caching.Distributed;
global using Educonnect.Common.Service.Helpers;
global using Educonnect.Common.Service.Context;
global using System.Data.SqlClient;
global using Educonnect.Common.Service.Application.Lookup.Queries;
global using Educonnect.Common.Service.Application.LeadQualification.Queries;
global using System.Text.Json;
global using Microsoft.EntityFrameworkCore;