version: '3.4'

services:
  redis:
    image: redis
    container_name: common-redis-cache
    ports:
      - "6379:6379"
  common-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/common-api
    ports:
      - "5101:80"
      - "9101:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    links:
      - "redis"
  educonnect.student.mobile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__common=http://common-service
    ports:
      - "5120:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "5102:80"
    - "9102:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  course-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/course-api
    ports:
      - "5104:80"
      - "9104:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - lucene_index:/app/lucene_index

  institute-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_PORT=81
      - PORT=80
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5105:80"
      - "9105:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  student-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5106:80"
      - "9106:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
    lucene_index:


